/**
 * Demo configuration for MMM-NINA module development
 * This config is used for testing the module in isolation
 *
 * Usage: node --run demo
 */

let config = {
  port: 8080,
  address: 'localhost',
  language: 'de',
  logLevel: ['INFO', 'LOG', 'WARN', 'ERROR'],
  timeFormat: 24,
  units: 'metric',

  modules: [
    {
      module: 'alert',
    },
    {
      module: 'clock',
      position: 'middle_center',
      config: {
        timeFormat: 'HH:mm:ss',
      },
    },

    // Top Left: Berlin
    {
      module: 'MMM-NINA',
      position: 'top_left',
      header: 'Warnungen Berlin',
      config: {
        ags: ['110000000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        // Demo: erhöhen, damit auch ältere Warnungen angezeigt werden
        maxAgeInHours: 240,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Top Left: Bremen
    {
      module: 'MMM-NINA',
      position: 'top_left',
      header: 'Warnungen Bremen',
      config: {
        ags: ['040110000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Top Left: Hannover
    {
      module: 'MMM-NINA',
      position: 'top_left',
      header: 'Warnungen Hannover',
      config: {
        ags: ['032410001001'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Top Right: Hamburg
    {
      module: 'MMM-NINA',
      position: 'top_right',
      header: 'Warnungen Hamburg',
      config: {
        ags: ['020000000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Top Right: Kiel
    {
      module: 'MMM-NINA',
      position: 'top_right',
      header: 'Warnungen Kiel',
      config: {
        ags: ['010020000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Top Right: Rostock
    {
      module: 'MMM-NINA',
      position: 'top_right',
      header: 'Warnungen Rostock',
      config: {
        ags: ['130030000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Bottom Left: Köln
    {
      module: 'MMM-NINA',
      position: 'bottom_left',
      header: 'Warnungen Köln',
      config: {
        ags: ['053150000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Bottom Left: Düsseldorf
    {
      module: 'MMM-NINA',
      position: 'bottom_left',
      header: 'Warnungen Düsseldorf',
      config: {
        ags: ['051110000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Bottom Left: Landkreis Sömmerda (zeigt die Warnung "Tierseuchengefahr")
    {
      module: 'MMM-NINA',
      position: 'bottom_left',
      header: 'Warnungen LK Sömmerda',
      config: {
        // AGS der Stadt Sömmerda; harmonizeAgs() kürzt für den API-Call auf 160680000000
        ags: ['160680051051'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        // Demo: 10 Tage, damit die Warnung sichtbar bleibt
        maxAgeInHours: 240,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Bottom Right: München
    {
      module: 'MMM-NINA',
      position: 'bottom_right',
      header: 'Warnungen München',
      config: {
        ags: ['091620000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Bottom Right: Stuttgart
    {
      module: 'MMM-NINA',
      position: 'bottom_right',
      header: 'Warnungen Stuttgart',
      config: {
        ags: ['081110000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
    // Bottom Right: Frankfurt
    {
      module: 'MMM-NINA',
      position: 'bottom_right',
      header: 'Warnungen Frankfurt',
      config: {
        ags: ['064120000000'],
        downgradeLhpSeverity: false,
        downgradeCancelSeverity: true,
        hideCancelledWarnings: false,
        excludeProviders: [],
        maxAgeInHours: 6,
        maxWidth: '350px',
        mergeAlertsById: true,
        mergeAlertsByTitle: true,
        orderBySeverity: true,
        showIcon: true,
        showDate: true,
        showCity: true,
        showNoWarning: true,
        theme: 'top',
        updateIntervalInSeconds: 120,
      },
    },
  ],
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {
  module.exports = config
}
